# SPDX-FileCopyrightText: 2026 The NazoOS Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

# zswap is redundant with zram (already compressed RAM) - disable it

w-   /sys/module/zswap/parameters/enabled    -     -    -      -     N
