# SPDX-FileCopyrightText: 2026 The NazoOS Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

# Compressed swap in RAM (see man zram-generator.conf)
[zram0]
zram-size = ram
compression-algorithm = zstd
swap-priority = 100
