# SPDX-FileCopyrightText: 2026 The NazoOS Contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Disclaimer page (DISCLAIMER.md, short version): must be accepted before
# the installation can go on. Local file = text is shown in the page.
# Docs: https://github.com/calamares/calamares/blob/calamares/src/modules/license/license.conf
---
entries:
  - id: nazoos-disclaimer
    name: NazoOS
    vendor: The NazoOS Contributors
    type: software
    url: file:///usr/share/calamares/branding/nazoos/disclaimer.html
    required: true
    expand: true
