# SPDX-FileCopyrightText: 2026 The NazoOS Contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Time zone and language; GeoIP preselects the time zone when online
---
region: "Europe"
zone: "Berlin"
geoip:
  style: "json"
  url: "https://geoip.kde.org/v1/calamares"
  selector: ""
