# SPDX-FileCopyrightText: 2026 The NazoOS Contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# First user. openSUSE asks for the root password in sudo and Polkit
# dialogs, so the root password is set to the user's password by default
# (like the openSUSE installer); the user can uncheck this.
---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - name: wheel
    must_exist: false
    system: true
  - video
  - audio

autologinGroup: autologin
doAutologin: false
setRootPassword: true
doReusePassword: true

passwordRequirements:
  minLength: 6
  maxLength: -1

allowWeakPasswords: true
allowWeakPasswordsDefault: false

user:
  shell: /bin/bash
  forbidden_names: [ root, nobody ]

hostname:
  location: Hostnamed
  writeHostsFile: true
  template: "nazoos-${cpu}"
